version: '3'
services:
  shortener:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - "redis"
    depends_on:
      - redis
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
